name: openvinodemo 
base: core24
version: '0.1'
summary: OpenVINO GenAI demo snap
description: |
  OpenVINO GenAI snap demo
grade: devel
confinement: strict

apps:
  openvinodemo:
    command: openvinodemo 
    # To allow the application to find TBB libraries, you can set the
    # LD_LIBRARY_PATH to the $SNAP directory, as below, or run
    # `patchelf --set-rpath "\$ORIGIN"` for all OpenVINO and TBB libraries
    # in the openvino_genai archive before building the snap
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP
    plugs:
      - home

parts:
  openvinodemo:
    plugin: cmake
    source: .
    build-packages: 
      - cmake
      - make
      - pkgconf
    override-build: |
      #!/bin/bash
      set +u
      source $CRAFT_PART_SRC/openvino_genai/setupvars.sh
      mkdir -p build && cd build
      cmake -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL $CRAFT_PART_SRC
      cmake --build . --config Release
      cmake --install .
